version: 1
provider_priority:
- antigravity
- Custom App
providers:
  antigravity:
    enabled: true
    process_name: Antigravity IDE.exe
    icon: pack://application:,,,/Assets/antigravity.png
    actions:
      accept:
        key_sequence:
        - Ctrl
        - T
      reject:
        key_sequence:
        - escape
  Custom App:
    enabled: true
    process_name: notepad.exe
    icon: pack://application:,,,/Assets/logo.ico
    actions:
      no:
        key_sequence:
        - Ctrl
        - T
hotkeys:
  Ctrl+Shift+Enter: accept
  Ctrl+Shift+P: no
settings:
  auto_start_on_boot: true
  show_tray_icon: true
